---

stages:
  - lint
  - molecule

yamllint:
  image: pipelinecomponents/yamllint:latest
  stage: lint
  script:
    - yamllint .

ansible-lint:
  image: pipelinecomponents/ansible-lint:latest
  stage: lint
  script:
    - ansible-lint .

molecule-test:
  image: debian:buster
  stage: molecule
  variables:
    ANSIBLE_STDOUT_CALLBACK: "debug"
    ANSIBLE_FORCE_COLOR: '1'
    PY_COLORS: '1'
  script:
    - apt-get update
    - apt-get install python3 python3-pip -y
    - pip3 install ansible molecule[docker] docker
    - molecule test
