---

stages:
  - lint
  - molecule

yamllint:
  image: pipelinecomponents/yamllint:latest
  stage: lint
  script:
    - yamllint .

ansible-lint:
  image: pipelinecomponents/ansible-lint:latest
  stage: lint
  script:
    - ansible-lint .

molecule-test:
  image: docker:stable-dind
  stage: molecule
  variables:
    ANSIBLE_STDOUT_CALLBACK: "debug"
    ANSIBLE_FORCE_COLOR: '1'
    PY_COLORS: '1'
  script:
    - apk add --no-cache python3 python3-dev py3-pip gcc git curl build-base autoconf automake py3-cryptography linux-headers musl-dev libffi-dev openssl-dev openssh
    - pip3 install ansible molecule[docker] docker
    - molecule test
