---
# tasks file for nginx

- name: Install certbot
  apt:
    name: certbot
    state: present
    update_cache: True
    cache_valid_time: 3600
  become: True

- name: install nginx
  apt:
    name: nginx
    state: present
    update_cache: True
    cache_valid_time: 3600
  become: True
  notify: restart nginx
