---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: check for running nginx
    uri:
      url: http://localhost
      status_code: 200
    register: result
    until: result.status == 200
    retries: 60
    delay: 1

  - name: Assert nginx is running
    assert:
      that: result.status == 200
